import pandas as pd
from setuptools import setup
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from dotenv import load_dotenv
from pathlib import Path
import os

# Load dotenv variables
load_dotenv()
SPOTIFY_USERNAME = os.getenv('SPOTIFY_USERNAME')
SPOTIFY_CLIENT_ID = os.getenv('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = os.getenv('SPOTIFY_CLIENT_SECRET')


def create_playlists():
    spotify = setup_spotify()

    # Combine csvs
    CSV_PATH = Path("data/wikipedia.csv")
    ADD_PATH = Path("data/manual_additions.csv")
    MERGED_PATH = Path("data/wiki_and_add.csv")
    combine_csvs(CSV_PATH, ADD_PATH, MERGED_PATH)

    # Read csv
    df = pd.read_csv(MERGED_PATH)
    grouped = df.groupby('Identity')
    identities = grouped.groups.keys()
    # identities = ['Intersex']

    for identity in identities:
        print(f'=== Creating {identity} Playlist ===')

        # Create playlist
        playlist_name = f"{identity} Artists"
        playlist_description = f"A collection of songs by {identity.lower()} artists. Generated by Queerify at Pride Hacks 2022."
        spotify.user_playlist_create(
            user=SPOTIFY_USERNAME,
            name=playlist_name,
            description=playlist_description,
            public=True)

        # Get playlist
        playlists = spotify.user_playlists(user=SPOTIFY_USERNAME)
        playlist_id = playlists['items'][0]['id']

        # Create df of identity
        df = grouped.get_group(identity)

        # Search for each artist in df and add their top song/s to playlist
        for artist in df['Artist']:
            try:
                search_res = spotify.search(q=artist, type='artist')
                artist_uri = search_res['artists']['items'][0]['uri']
            except:
                print(f'-- No results found for {artist}')
                continue

            # Calculate num tracks to add, depending on number of artists
            num_artists = len(df['Artist'])
            if num_artists < 5:
                num_tracks_to_add = 4
            elif num_artists < 10:
                num_tracks_to_add = 3
            elif num_artists < 20:
                num_tracks_to_add = 2  
            else:
                num_tracks_to_add = 1

            # Add top song/s by artist to playlist
            num_tracks_added = 0
            track_res = spotify.artist_top_tracks(artist_uri)
            for track in track_res['tracks']:
                # Ignore songs with multiple artists
                if len(track['artists']) > 1:
                    continue
                # Get track uri and add to playlist
                track_uri = track['uri']
                track_name = track['name']
                spotify.user_playlist_add_tracks(
                    user=SPOTIFY_USERNAME,
                    playlist_id=playlist_id,
                    tracks=[track_uri])
                num_tracks_added += 1
                print(f'+ Added {track_name} by {artist}')

                if num_tracks_added == num_tracks_to_add:
                    break


def setup_spotify():
    redirect_uri = 'http://localhost:8888/callback'
    scope = 'playlist-modify-public'

    # Get token and set up Spotify object
    token = SpotifyOAuth(
        client_id=SPOTIFY_CLIENT_ID,
        client_secret=SPOTIFY_CLIENT_SECRET,
        scope=scope,
        redirect_uri=redirect_uri,
        username=SPOTIFY_USERNAME)
    spotify = spotipy.Spotify(auth_manager=token)

    return spotify


def combine_csvs(path1, path2, merged_path):
    try:
        # Concatenate 2 given csvs
        df1 = pd.read_csv(path1)
        df2 = pd.read_csv(path2)
        pd.concat([df1, df2]).to_csv(merged_path, index=False)
        return True
    except:
        return False


create_playlists()
